language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "6.9.5"
  - "6"
  - "8"
  - "node"
env:
  - CXX=g++-4.8 REDIS_ENDPOINT=redis://localhost:6379/0
services:
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: make test
after_success:
  npm run send_cover